import { createCore } from './core.js';
const storageKey = 'mithril-todo-pages-v1';
const sample = () => [
 {id:'sample-1',title:'今日やりたいことを書き出す',status:'pending'},
 {id:'sample-2',title:'小さな一歩から始める',status:'in_progress'},
 {id:'sample-3',title:'できたことを振り返る',status:'completed'}
];
let tasks = sample(), filter = 'all', core, module;
try { const stored = JSON.parse(localStorage.getItem(storageKey)); if(Array.isArray(stored)&&stored.every(x=>typeof x.id==='string'&&typeof x.title==='string'&&['pending','in_progress','completed'].includes(x.status))) tasks=stored; } catch { /* Unavailable or invalid browser storage uses the sample. */ }
const q = s => document.querySelector(s);
const statusCode = {pending:1,in_progress:2,completed:3};
function guest(name,...args){const f=new WebAssembly.Instance(module).exports[name];if(typeof f!=='function')throw new Error('Missing Mithril policy');return Number(f(...args.map(BigInt)));}
function diff(previous,current){const old=new Map(previous.map(x=>[x.id,x])),currentIds=new Set(current.map(x=>x.id)),ranks=new Map();let rank=0;for(const x of previous){rank=guest('todo-rank',rank,Number(currentIds.has(x.id)));ranks.set(x.id,rank-1);}rank=0;const counts={added:0,updated:0,moved:0,removed:0};for(const x of current){const before=old.get(x.id);old.delete(x.id);const value=guest('todo-change',Number(before!==undefined),before?statusCode[before.status]:0,statusCode[x.status],ranks.get(x.id)??-1,rank);rank=guest('todo-rank',rank,Number(before!==undefined));if(value===1)counts.added++;if(value===2)counts.updated++;if(value===3)counts.moved++;}counts.removed=old.size;return Object.entries(counts).filter(([,n])=>n).map(([key,n])=>`${({added:'追加',updated:'状態変更',moved:'並べ替え',removed:'削除'})[key]} ${n}件`).join(' · ')||'変更なし';}
function render(){if(!core||!module)return;const remaining=core.remaining(tasks.map(x=>x.status==='completed')),done=tasks.length-remaining;q('#all-count').textContent=tasks.length;q('#active-count').textContent=remaining;q('#done-count').textContent=done;q('#progress-text').textContent=`${done} / ${tasks.length} 完了 · 残り ${remaining}件`;q('#progress').style.width=`${tasks.length?done/tasks.length*100:0}%`;q('#list-heading').textContent=({all:'すべてのタスク',active:'未完了のタスク',done:'完了したタスク'})[filter];document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.setAttribute('aria-pressed',String(b.dataset.filter===filter));});const visible=tasks.filter(x=>filter==='all'||(filter==='done')===(x.status==='completed'));q('#tasks').replaceChildren();q('#empty').hidden=visible.length>0;for(const x of visible){const row=document.createElement('li');row.className=`task ${x.status}`;row.dataset.id=x.id;const checkbox=document.createElement('button');checkbox.className='check';checkbox.setAttribute('role','checkbox');checkbox.setAttribute('aria-checked',String(x.status==='completed'));checkbox.setAttribute('aria-label',`${x.title}の完了を切り替える`);checkbox.textContent=x.status==='completed'?'✓':'';checkbox.onclick=()=>change(()=>{x.status=core.toggle(x.status==='completed')?'completed':'pending';});const title=document.createElement('span');title.className='task-title';title.textContent=x.title;const status=document.createElement('span');status.className='status-pill';status.textContent=({pending:'未着手',in_progress:'進行中',completed:'完了'})[x.status];const actions=document.createElement('div');actions.className='row-actions';if(x.status==='pending'){const start=document.createElement('button');start.textContent='開始';start.setAttribute('aria-label',`${x.title}を開始`);start.onclick=()=>change(()=>{x.status='in_progress';});actions.append(start);}for(const [offset,text]of[[-1,'↑'],[1,'↓']]){const b=document.createElement('button');b.textContent=text;b.setAttribute('aria-label',`${x.title}を${offset===-1?'上':'下'}へ`);const index=tasks.indexOf(x);b.disabled=index+offset<0||index+offset>=tasks.length;b.onclick=()=>change(()=>{[tasks[index],tasks[index+offset]]=[tasks[index+offset],tasks[index]];});actions.append(b);}const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label',`${x.title}を削除`);remove.onclick=()=>change(()=>{tasks=tasks.filter(t=>t.id!==x.id);});actions.append(remove);row.append(checkbox,title,status,actions);q('#tasks').append(row);}}
function change(mutator){if(!core||!module)return;const previous=tasks.map(x=>({...x}));mutator();let saved=true;try{localStorage.setItem(storageKey,JSON.stringify(tasks));}catch{saved=false;}render();q('#feedback').textContent=`Mithril判定: ${diff(previous,tasks)}${saved?'':' · このブラウザーでは保存できません'}`;}
q('#add-form').onsubmit=e=>{e.preventDefault();const title=q('#task-input').value.trim();if(!title)return;change(()=>tasks.push({id:crypto.randomUUID(),title,status:'pending'}));q('#task-input').value='';q('#task-input').focus();};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});q('#reset').onclick=()=>change(()=>{tasks=sample();filter='all';});
async function boot(){const [logic,metrics,bytes]=await Promise.all([fetch('./logic.json').then(r=>r.json()),fetch('./metrics.json').then(r=>r.json()),fetch('./policy.wasm').then(r=>r.arrayBuffer())]);core=createCore(logic);module=new WebAssembly.Module(bytes);const expected=metrics.policy.wasm_sha256;const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');if(digest!==expected)throw new Error('Mithril artifact digest mismatch');render();q('#feedback').textContent='Jev組立ロジックとMithril判定で実行中';q('#jev-time').textContent=`${metrics.jev.runner_seconds.toFixed(2)} 秒`;q('#jev-decisions').textContent=`${metrics.jev.decisions}判断 · ${metrics.jev.attempts}試行 · 2ファイル`;q('#jev-cost').textContent=`$${metrics.jev.api_cost_usd.toFixed(6)}`;q('#jev-tokens').textContent=`入力 ${metrics.jev.input_tokens.toLocaleString()} / 出力 ${metrics.jev.output_tokens.toLocaleString()} tokens`;q('#dev-time').textContent=metrics.development.wall_seconds===null?'計測中':`${Math.floor(metrics.development.wall_seconds/60)}分 ${Math.round(metrics.development.wall_seconds%60)}秒`;q('#checks-summary').textContent='生成したロジックは完了切替と511通りの状態一覧を検査。画面の追加・切替・削除・並べ替え・再読み込みもブラウザーで検証しています。';q('#build-id').textContent=metrics.build_id;window.mithrilTodoReady=true;}
boot().catch(error=>{q('#feedback').textContent='読み込みに失敗しました。再読み込みしてください。';q('#add-form button').disabled=true;console.error(error);});
