'use strict';
const $=id=>document.getElementById(id);
let revision=null,offset=0,next=null,selected=null,request={operation:'catalog'},generation=0;
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
async function api(body,endpoint='/query',bind=true){
 const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(bind&&revision?{...body,revision}:body)}),data=await r.json();
 if(!r.ok){if(r.status===409)$('notice').textContent='The index changed. Select Refresh sources to continue.';throw new Error(data.message||data.error);}
 return data;
}
function showError(e){$('notice').textContent=e.message;}
function resultButton(title,subtitle,action,snippet){const b=node('button',undefined,'result');b.append(node('strong',title),node('small',subtitle));if(snippet)b.append(node('p',snippet,'snippet'));b.onclick=()=>Promise.resolve(action()).catch(showError);return b;}
async function status(){const s=await api({operation:'status'},'/query',false);revision=s['snapshot-digest'];$('metrics').replaceChildren(...[['files','Files'],['nodes','Items'],['edges','relationships'],['unresolved-count','Unresolved']].map(([k,label])=>node('span',`${s[k].toLocaleString()} ${label}`)));$('revision').textContent=`Snapshot ${revision} · Changes appear after an explicit refresh`; $('diagnostics').textContent=JSON.stringify({classifications:s['unresolved-by-classification'],reasons:s['diagnostics-by-reason'],diagnostics:s.diagnostics},null,2);}
async function browse(){const ticket=++generation,r=await api({...request,offset,limit:30});if(ticket!==generation)return;next=r['next-offset'];$('results').replaceChildren();
 for(const n of r.nodes||[])$('results').append(resultButton(n.label||n.name,`${n.kind} · ${n.path}`,()=>inspect(n.id)));
 for(const m of r.matches||[])$('results').append(resultButton(`${m.path}:${m.span['start-line']}:${m.span['start-column']}`,'Exact text match / saved source',()=>inspect(m.file,m),m.snippet));
 for(const c of r.communities||[])$('results').append(resultButton(`${c.size}-file community`,c.id,()=>community(c.id)));
 if(!$('results').children.length)$('results').append(node('p','No matching items.'));
 $('page').textContent=`${offset+1}–${offset+$('results').children.length}`;$('prev').disabled=offset===0;$('next').disabled=next==null;$('notice').textContent='Search covers the complete index. Use pagination to see more results.';}
async function inspect(id,match){const ticket=++generation,r=await api({operation:'node',node:id});if(ticket!==generation)return;selected=r.node.id;$('title').textContent=r.node.label||r.node.name;$('location').textContent=`${r.node.path}${r.node.span?`:${r.node.span['start-line']}`:''} · ${r.node['source-digest']}`;$('source').textContent=match?match.snippet:r.source;$('precision').textContent=match?`Match location ${match.span['start-line']}:${match.span['start-column']}–${match.span['end-column']} · Revision-bound exact match`:`Location precision: ${r.node['location-precision']||'syntax'}${r['source-truncated']?' · Source display truncated by its limit':''}`;$('impact').disabled=false;$('neighbors').disabled=false;await related('neighbors',ticket);}
function draw(nodes,edges){const container=$('graph');container.replaceChildren();if(!nodes.length)return;const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 280');svg.setAttribute('role','img');svg.setAttribute('aria-label','Direct relationships of the selected item. Up to 30 items.');const positions=new Map(nodes.slice(0,30).map((n,i,a)=>[n.id,{n,x:300+190*Math.cos(2*Math.PI*i/a.length),y:140+100*Math.sin(2*Math.PI*i/a.length)}]));
 for(const e of edges){const a=positions.get(e.source),b=positions.get(e.target);if(!a||!b)continue;const l=document.createElementNS(ns,'line');for(const [k,v]of Object.entries({x1:a.x,y1:a.y,x2:b.x,y2:b.y}))l.setAttribute(k,v);svg.append(l);}
 for(const {n,x,y}of positions.values()){const g=document.createElementNS(ns,'g'),c=document.createElementNS(ns,'circle'),t=document.createElementNS(ns,'text');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r',6);t.setAttribute('x',x+8);t.setAttribute('y',y+4);t.textContent=(n.label||n.name).slice(-24);g.append(c,t);g.onclick=()=>inspect(n.id).catch(showError);svg.append(g);}container.append(svg,node('small','Diagram shows up to 30 items. More relationships are listed below.'));}
async function related(operation,ticket=generation,edgeOffset=0){if(!selected)return;const r=await api({operation,node:selected,offset:edgeOffset,limit:30});if(ticket!==generation)return;$('relations').replaceChildren(node('h3',operation==='impact'?'Impact':'Direct relationships'));
 const all=new Map((r.nodes||[]).map(n=>[n.id,n]));if(operation==='impact'){for(const n of r.nodes)$('relations').append(resultButton(n.label||n.name,n.path,()=>inspect(n.id)));$('graph').replaceChildren();}
 else {draw(r.nodes||[],r.edges||[]);for(const e of r.edges||[]){const id=e.source===selected?e.target:e.source,n=all.get(id);$('relations').append(resultButton(n?.label||n?.name||id,`${e.relation} · ${e.path}:${e.span['start-line']}`,()=>inspect(id)));}}
 if(r['next-offset']!=null){const b=node('button','More relationships');b.onclick=()=>related(operation,ticket,r['next-offset']).catch(showError);$('relations').append(b);}else if(r.truncated)$('relations').append(node('p','Exploration limit reached. Select a node to continue from there.'));}
async function community(id){const r=await api({operation:'community',community:id});selected=null;$('title').textContent=`Community · ${r.community.size} Files`;$('source').textContent='Structural community candidate. It does not prove semantic identity or runtime coupling.';$('location').textContent=id;$('precision').textContent='';$('impact').disabled=true;$('neighbors').disabled=true;$('relations').replaceChildren(...r.nodes.map(n=>resultButton(n.name,n.path,()=>inspect(n.id))));draw(r.nodes,r.edges);if(r.truncated)$('relations').append(node('p','View truncated by its limit. Explore individual files for the complete index.'));}
$('search').onsubmit=e=>{e.preventDefault();offset=0;const mode=$('mode').value,q=$('query').value;request=mode==='communities'?{operation:mode}:q?{operation:mode,query:q}:{operation:'catalog'};browse().catch(showError);};$('next').onclick=()=>{offset=next;browse().catch(showError);};$('prev').onclick=()=>{offset=Math.max(0,offset-30);browse().catch(showError);};$('impact').onclick=()=>related('impact').catch(showError);$('neighbors').onclick=()=>related('neighbors').catch(showError);
$('refresh').onclick=async()=>{const b=$('refresh');b.disabled=true;$('notice').textContent='Refreshing sources…';++generation;try{await api({},'/refresh',false);selected=null;$('impact').disabled=true;$('neighbors').disabled=true;$('title').textContent='Select an item';$('source').textContent='';$('location').textContent='';$('precision').textContent='';$('graph').replaceChildren();$('relations').replaceChildren();await status();offset=0;await browse();}catch(e){showError(e);}finally{b.disabled=false;}};
status().then(browse).catch(showError);
