import assert from'node:assert/strict';import{writeFileSync,mkdtempSync,rmSync}from'node:fs';import{resolve,join}from'node:path';import{tmpdir}from'node:os';import{pathToFileURL,fileURLToPath}from'node:url';
const[entry,compiler,typeRoots,receiver='Context']=process.argv.slice(2),ts=(await import(pathToFileURL(resolve(compiler)))).default,fixture=fileURLToPath(new URL('../../../fixtures/cordis-declarations/',import.meta.url)),dir=mkdtempSync(join(tmpdir(),'mithril-augmentation-private-'));
try{
 const target=join(fixture,'program/context.js'),reference=join(dir,'reference.d.mts');
 for(const[name,datatype]of[['left','string'],['right','number']]){const owner=receiver==='Alias'?reference.replace(/\.d\.mts$/,'.mjs'):target,view=receiver==='Alias'&&name==='left'?'Alias':'Context';writeFileSync(join(dir,name+'.d.mts'),`import ${JSON.stringify(owner)};declare const Token:unique symbol;type Local=${datatype};declare module ${JSON.stringify(owner)} {interface ${view} {${name}:Local;${name}Token:typeof Token;}}export {};`);}
 writeFileSync(reference,`import './left.mjs';import './right.mjs';export {Context} from ${JSON.stringify(target)};export type {Context as Alias} from ${JSON.stringify(target)};`);
 const cases=[['left private type',true,'const a:string=c.left;'],['right private type',receiver!=='Alias','const a:number=c.right;'],['same token identity',true,'const a:typeof c.leftToken=c.leftToken;'],['right token identity',receiver!=='Alias','const a:typeof c.rightToken=c.rightToken;'],['wrong left private type',false,'const a:number=c.left;'],['wrong right private type',false,'const a:string=c.right;'],['foreign token differs',false,'const a:typeof c.leftToken=c.rightToken;'],['private alias remains hidden',false,'let a:api.Local;']];
 const files=[];for(const[name,ok,body]of cases)for(const variant of ['original','candidate']){const file=join(dir,variant+'-'+files.length+'.ts'),root=variant==='original'?reference:resolve(entry);writeFileSync(file,'import * as api from '+JSON.stringify(root.replace(/\.d\.mts$/,'.mjs'))+';declare const c:api.'+receiver+';'+body);files.push({file,name,ok,variant});}
 const paths=Object.fromEntries(['context','events','logger','reflect','registry','fiber','utils','service'].map(n=>['@augmentation/'+n,[join(fixture,'program',n+'.d.ts')]]));paths['@deepseek-ai/cosmokit']=[resolve(fixture,'../cosmokit-declarations/index.d.ts')];paths['@standard-schema/spec']=[join(fixture,'standard-schema/index.d.ts')];
 const p=ts.createProgram(files.map(x=>x.file),{strict:true,noEmit:true,skipLibCheck:false,target:ts.ScriptTarget.ES2024,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,allowImportingTsExtensions:true,types:['node'],typeRoots:[resolve(typeRoots)],paths}),ds=ts.getPreEmitDiagnostics(p),negative=new Set(files.filter(x=>!x.ok).map(x=>x.file));assert.deepEqual(ds.filter(d=>!d.file||!negative.has(d.file.fileName)).map(d=>({file:d.file?.fileName,code:d.code,text:ts.flattenDiagnosticMessageText(d.messageText,' ')})),[]);
 for(const[name,ok]of cases)if(!ok){const pair=files.filter(x=>x.name===name),codes=c=>ds.filter(d=>d.file?.fileName===c.file).map(d=>d.code).sort((a,b)=>a-b);assert(codes(pair[0]).length,name);assert.deepEqual(codes(pair[0]),codes(pair[1]),name);}
 console.log('Augmentation lexical oracle:8 original-paired private type/unique symbol groups;separate source frames and hidden private aliases.');
}finally{rmSync(dir,{recursive:true,force:true});}
