import assert from'node:assert/strict';import{readFileSync,writeFileSync,mkdtempSync,rmSync,readdirSync}from'node:fs';import{resolve,join}from'node:path';import{pathToFileURL,fileURLToPath}from'node:url';import{tmpdir}from'node:os';import{createHash}from'node:crypto';
const[manifest,compiler,typeRoots]=process.argv.slice(2),ts=(await import(pathToFileURL(resolve(compiler)))).default;assert.equal(ts.version,'6.0.3');const items=JSON.parse(readFileSync(manifest,'utf8')),fixture=fileURLToPath(new URL('../../../fixtures/default-exports/',import.meta.url)),provenance=JSON.parse(readFileSync(join(fixture,'provenance.json'),'utf8'));for(const[f,h]of Object.entries(provenance.fixtures))assert.equal(createHash('sha256').update(readFileSync(join(fixture,f))).digest('hex'),h);
const dir=mkdtempSync(join(tmpdir(),'mithril-default-contract-'));try{
 for(const f of Object.keys(provenance.fixtures))writeFileSync(join(dir,f),readFileSync(join(fixture,f)));
 const opts={strict:true,skipLibCheck:false,target:ts.ScriptTarget.ES2024,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,declaration:true,types:['node'],typeRoots:[resolve(typeRoots)]},oracle=ts.createProgram(Object.keys(provenance.fixtures).map(f=>join(dir,f)),opts);assert.deepEqual(ts.getPreEmitDiagnostics(oracle),[]);assert.equal(oracle.emit().emitSkipped,false);writeFileSync(join(dir,'package.json'),'{"type":"module"}');
 const positives=[['default instance','const actual=new D({tag:"x"});const x:"x"=actual.value.tag;'],['default type','declare const x:D<string>;const y:string=x.value;'],['default generic default','declare const x:D;const y:unknown=x.value;'],['named class identity typing','const x:D<string>=new api.Named("x");'],['static const method','const actual=D.capture({tag:"x"});const x:"x"=actual.tag;'],['module namespace default query','const C:typeof api.default=D;const x:D<string>=new C("x");'],['inline default type','type X=import(ENTRY).default<string>;const x:X=new D("x");'],['inline default value query','type C=typeof import(ENTRY).default;const x:C=D;'],['count numeric','const x:number=api.count;'],['bump numeric','const x:number=api.bump();'],['explicit generic override','const x=new D<{tag:string}>({tag:"x"});x.value.tag="y";'],['readonly payload accepted','const x=new D(["x",42]);const y:readonly ["x",42]=x.value;']];
 const negatives=[['default instance wrong','declare const x:D<string>;const y:number=x.value;'],['readonly property','new D("x").value="x";'],['const literal mutation','new D({tag:"x"}).value.tag="x";'],['constructor missing','new D();'],['static readonly','D.capture({tag:"x"}).tag="x";'],['generic arity','type X=D<string,number>;'],['inline generic arity','type X=import(ENTRY).default<string,number>;'],['count wrong','const x:string=api.count;'],['private nominal owner','declare class Other{readonly value:string;private brand:undefined}declare const other:Other;const x:D<string>=other;']];
 const extra=[['positive','default alias renamed','const x:D<string>=new api.Renamed("x");'],['positive','namespace imported constructor','declare const C:api.NamespaceConstructor;const x:D<string>=new C("x");'],['positive','named default imported constructor','declare const C:api.ImportedConstructor;const x:D<string>=new C("x");'],['negative','inline instance wrong','declare const x:api.InlineInstance;const y:number=x.value;']];
 const groups=[];for(const [index,item]of items.entries())for(const [category,name,body]of(item.profile.startsWith('enum')?[['positive','enum default constant','const x:1=D.ONE;'],['positive','enum default member type','const x:D.ONE=D.ONE;'],['negative','enum default invalid value','const x:D=3;'],['negative','enum default member mismatch','const x:D.ONE=D.TWO;']]:item.profile==='type-only'?[['positive','type-only default instance','declare const x:D<string>;const y:string=x.value;'],['positive','type-only default value query','declare const C:typeof D;type X=InstanceType<typeof C>;'],['negative','type-only default construction','new D(1);'],['negative','type-only default mismatch','declare const x:D<string>;const y:number=x.value;']]:[...positives.map(([n,b])=>['positive',n,b]),...negatives.map(([n,b])=>['negative',n,b]),...(item.profile==='program'?extra:[])]))for(const variant of ['original','candidate']){const entry=resolve(variant==='original'?join(dir,item.profile==='program'?'index.js':item.profile.startsWith('enum')?'enum.js':item.profile==='type-only'?'type-only.js':'direct.js'):item.types.replace(/\.d\.mts$/,'.mjs'));const file=join(dir,`consumer-${groups.length}.ts`);writeFileSync(file,'import D,* as api from '+JSON.stringify(entry)+';\n'+body.replaceAll('ENTRY',JSON.stringify(entry)));groups.push({index,category,name,variant,file})}
 const p=ts.createProgram(groups.map(g=>g.file),{...opts,noEmit:true}),diagnostics=ts.getPreEmitDiagnostics(p),neg=new Set(groups.filter(g=>g.category==='negative').map(g=>g.file));assert.deepEqual(diagnostics.filter(d=>!d.file||!neg.has(d.file.fileName)).map(d=>({file:d.file?.fileName,code:d.code,text:ts.flattenDiagnosticMessageText(d.messageText,' ')})),[]);
 for(const item of groups.filter(g=>g.category==='negative'&&g.variant==='original')){const candidate=groups.find(g=>g.index===item.index&&g.name===item.name&&g.variant==='candidate'),codes=g=>diagnostics.filter(d=>d.file?.fileName===g.file).map(d=>d.code).sort((a,b)=>a-b);assert(codes(item).length,item.name);assert.deepEqual(codes(candidate),codes(item),item.name)}
 const checker=p.getTypeChecker(),surface=file=>checker.getExportsOfModule(checker.getSymbolAtLocation(p.getSourceFile(resolve(file)))).map(s=>{const x=s.flags&ts.SymbolFlags.Alias?checker.getAliasedSymbol(s):s;return{name:s.name,type:!!(x.flags&ts.SymbolFlags.Type),value:!!(x.flags&ts.SymbolFlags.Value)}}).sort((a,b)=>a.name.localeCompare(b.name));for(const item of items)assert.deepEqual(surface(item.types),surface(join(dir,item.profile==='program'?'index.ts':item.profile.startsWith('enum')?'enum.ts':item.profile==='type-only'?'type-only.ts':'direct.ts')));
 for(const item of items.filter(x=>x.runtime)){const original=await import(pathToFileURL(join(dir,item.profile==='program'?'index.js':item.profile.startsWith('enum')?'enum.js':item.profile==='type-only'?'type-only.js':'direct.js'))),candidate=await import(pathToFileURL(resolve(item.runtime)));for(const m of [original,candidate]){if(item.profile==='type-only'||item.profile.startsWith('enum')){assert.deepEqual(Object.keys(m),[]);continue}assert.deepEqual(Object.keys(m).sort(),(item.profile==='program'?['Named','Renamed','bump','count','default']:['Named','bump','count','default']).sort());assert.equal(m.default,m.Named);if(item.profile==='program')assert.equal(m.default,m.Renamed);const x=new m.default({tag:'x'});assert(x instanceof m.Named);assert.deepEqual(x.value,{tag:'x'});assert.equal(m.default.capture(x.value),x.value);const before=m.count;assert.equal(m.bump(),before+1);assert.equal(m.count,before+1);assert.equal(Object.prototype.toString.call(m),'[object Module]');assert.equal(m.default.name,'Schema')}}
 for(const [index,item] of items.entries())if(item.profile.startsWith('enum'))for(const variant of ['original','candidate']){const entry=variant==='original'?join(dir,'enum.js'):item.types.replace(/\.d\.mts$/,'.mjs'),file=join(dir,`fold-${index}-${variant}.ts`);writeFileSync(file,'import D from '+JSON.stringify(entry)+';export const value=D.ONE;');const p=ts.createProgram([file],{...opts,declaration:false});assert.deepEqual(ts.getPreEmitDiagnostics(p),[]);let output='';assert.equal(p.emit(undefined,(f,text)=>{if(f.endsWith('.js'))output=text}).emitSkipped,false);assert(!/\bimport\b/.test(output));const out=join(dir,`fold-${index}-${variant}.mjs`);writeFileSync(out,output);assert.equal((await import(pathToFileURL(out))).value,1)}
 console.log(`Default export oracle:${groups.length/2} trusted original-paired strict logical groups across${items.length} CLI declaration artifacts;private dual class/type/value default identity,default import/reexport/namespace/inline/entry selection and${items.filter(x=>x.runtime&&x.profile!=='type-only'&&!x.profile.startsWith('enum')).length*8+items.filter(x=>x.runtime&&(x.profile==='type-only'||x.profile.startsWith('enum'))).length+items.filter(x=>x.profile.startsWith('enum')).length} paired runtime groups with live aliases;operator mechanics fixture,not full Schema.`);
}finally{rmSync(dir,{recursive:true,force:true})}
