import assert from 'node:assert/strict';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const proof=JSON.parse(readFileSync(new URL('../../../fixtures/private-fields/provenance.json',import.meta.url),'utf8'));
for(const[file,sha]of Object.entries(proof.fixtures))assert.equal(createHash('sha256').update(readFileSync(new URL('../../../fixtures/private-fields/'+file,import.meta.url))).digest('hex'),sha);
for(const[file,sha]of Object.entries(proof.mithrilSources))assert.equal(createHash('sha256').update(readFileSync(new URL('../../../../examples/'+file,import.meta.url))).digest('hex'),sha);
const original=await import(new URL('../../../fixtures/private-fields/oracle.mjs',import.meta.url));
const candidate=(await import(pathToFileURL(resolve(process.argv[2])))).instantiateMithrilNative({});
function run(api){
 const {Counter:C,Other,Derived,MethodFirst,FieldTooEarly,Pair,ComputedNames,PrivateNames,StaticBlock}=api,groups=[];
 const check=(name,body)=>{body();groups.push(name)},typeError=body=>assert.throws(body,error=>error.name==='TypeError');
 check('invisible fields',()=>{const c=new C;assert.deepEqual(Reflect.ownKeys(c),[]);c['#x']=99;assert.equal(c.get(),1);assert.deepEqual(Reflect.ownKeys(c),['#x'])});
 check('forged receiver',()=>typeError(()=>new C().get(Object.create(C.prototype))));
 check('proxy receiver',()=>typeError(()=>new C().get(new Proxy(new C(),{}))));
 check('primitive receivers',()=>{for(const value of [null,undefined,0,'x'])typeError(()=>new C().read(value))});
 check('distinct owner',()=>typeError(()=>new C().get(new Other)));
 check('derived brand',()=>assert.equal(new Derived().get(),1));
 check('numeric updates',()=>{const c=new C;assert.equal(c.post(),1);assert.equal(c.pre(),3);assert.equal(c.get(),3)});
 check('compound evaluation',()=>{const c=new C,trace=[];assert.equal(c.compound(()=>{trace.push('receiver');return c},()=>{trace.push('rhs');return 2}),3);assert.deepEqual(trace,['receiver','rhs'])});
 check('compound abrupt receiver',()=>{let calls=0;typeError(()=>new C().compound(()=>({}),()=>{calls++;return 2}));assert.equal(calls,0)});
 check('logical short circuit',()=>{const c=new C;assert.equal(c.logical(()=>{throw Error('unexpected rhs')}),1);c.set(0);let calls=0;assert.equal(c.logical(()=>{calls++;return 7}),7);assert.equal(calls,1)});
 check('optional private read',()=>{const c=new C;assert.equal(c.optional(null),undefined);assert.equal(c.optional(c),1);typeError(()=>c.optional({}))});
 check('optional private call receiver',()=>{const c=new C;assert.equal(c.optionalMethod(null),undefined);assert.equal(c.optionalMethod(c),1);typeError(()=>c.optionalMethod({}))});
 check('arrow lexical this',()=>assert.equal(new C().arrow().call({}),1));
 check('ordinary function and parameter default',()=>{const c=new C,f=c.ordinary();assert.equal(f.call(c),1);assert.equal(f.call({},c),1);typeError(()=>f.call({}))});
 check('object method private environment',()=>{const c=new C;assert.equal(c.object().read(c),1)});
 check('nested owner shadowing',()=>{const c=new C,Inner=c.nested(),i=new Inner;assert.equal(i.get(i),9);typeError(()=>i.get(c));assert.equal(Array.isArray(i.outer(c)),true)});
 check('private method receiver and name',()=>{const c=new C,f=c.detached();assert.equal(f.name,'#method');assert.equal(c.method(c),1);assert.equal(f.call(c),1);typeError(()=>f.call({}))});
 check('private method spread',()=>{const c=new C;assert.equal(c.spreadMethod(c,[1,2]),1);typeError(()=>c.spreadMethod({},[]))});
 check('static private owner',()=>{assert.equal(C.read(),4);typeError(()=>Derived.read())});
 check('private method initialization',()=>assert.equal(new MethodFirst().get(),7));
 check('private field initialization order',()=>typeError(()=>new FieldTooEarly));
 check('computed-key private environment',()=>assert.equal(typeof new ComputedNames()[''],'function'));
 check('getter setter pair',()=>{const p=new Pair;assert.equal(p.inc(),1);assert.deepEqual(p.trace,['get','set'])});
 check('Unicode and dollar private identifiers',()=>assert.equal(new PrivateNames().get(),5));
 check('static block owner',()=>assert.equal(StaticBlock.get(),5));
 check('computed key retains enclosing normal-function this',()=>{const Inner=api.computedWithReceiver.call({key:'read'});assert.equal(new Inner().read(),7)});
 const shape=object=>Reflect.ownKeys(object).filter(k=>k!=='prototype').map(key=>{const d=Object.getOwnPropertyDescriptor(object,key);return{key:typeof key==='symbol'?String(key):key,enumerable:d.enumerable,configurable:d.configurable,writable:d.writable,value:typeof d.value==='function'?{name:d.value.name,length:d.value.length}:typeof d.value,get:d.get&&{name:d.get.name,length:d.get.length},set:d.set&&{name:d.set.name,length:d.set.length}}});
 return{groups,surface:Object.keys(api).sort().map(name=>({name,shape:shape(api[name]),prototype:shape(api[name].prototype)}))};
}
const expected=run(original),actual=run(candidate);assert.deepEqual(actual,expected);assert.equal(actual.groups.length,26);
console.log('Private fields: 26 independent native-JavaScript-paired groups, complete class descriptors and native brand/scope/initialization/receiver/update/optional-call semantics; Node execution only.');
