import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,rmSync} from 'node:fs';
import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {pathToFileURL,fileURLToPath} from 'node:url';
import {cases,prefix,augmentation} from './cases.mjs';
const [compiler,typeRoots,candidate,brand]=process.argv.slice(2),ts=(await import(pathToFileURL(resolve(compiler)))).default;assert.equal(ts.version,'6.0.3');
const repo=fileURLToPath(new URL('../../../../',import.meta.url)),fixture=join(repo,'test/fixtures/protocol-sdk'),meta=JSON.parse(readFileSync(candidate+'.log','utf8')),bm=JSON.parse(readFileSync(brand+'.log','utf8'));
const options={target:ts.ScriptTarget.ES2024,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,allowImportingTsExtensions:true,noEmit:true,strict:true,skipLibCheck:false,typeRoots:[resolve(typeRoots)],types:['node']};
const dir=mkdtempSync(join(tmpdir(),'protocol-types-'));try{
 const files=cases.map((_,i)=>join(dir,'consumer-'+i+'.mts')),aug=join(dir,'augmentation.mts');writeFileSync(aug,augmentation);
 const originalMapping={'@deepseek-ai/dsh-typert-protocol':join(fixture,'index.d.ts'),'@deepseek-ai/dsh-brand':join(repo,'test/fixtures/brand-sdk/index.d.ts'),'@deepseek-ai/cordis':join(repo,'test/fixtures/cordis-declarations/program/index.d.ts'),'@deepseek-ai/cosmokit':join(repo,'test/fixtures/cosmokit-declarations/index.d.ts'),'@standard-schema/spec':join(repo,'test/fixtures/cordis-declarations/standard-schema/index.d.ts')};
 const candidateMapping={...originalMapping,'@deepseek-ai/dsh-typert-protocol':join(candidate,meta['module-files']['protocol.index']),'@deepseek-ai/dsh-brand':join(brand,bm['module-files']['brand.index'])};
 for(const[name,id]of [['@deepseek-ai/cordis','cordis.index'],['@deepseek-ai/cosmokit','cosmokit'],['@standard-schema/spec','standard.schema']])candidateMapping[name]=join(candidate,meta['module-files'][id]);
 function check(mapping){const host=ts.createCompilerHost(options),read=host.readFile,exists=host.fileExists;host.readFile=file=>files.includes(file)?prefix+cases[files.indexOf(file)][1]:read(file);host.fileExists=file=>files.includes(file)||exists(file);host.resolveModuleNames=(names,source)=>names.map(name=>mapping[name]?{resolvedFileName:mapping[name],extension:mapping[name].endsWith('.mts')?ts.Extension.Dmts:ts.Extension.Dts,isExternalLibraryImport:true}:ts.resolveModuleName(name,source,options,host).resolvedModule);const p=ts.createProgram([...files,aug],options,host),groups=files.map(()=>[]);for(const d of ts.getPreEmitDiagnostics(p)){const i=files.indexOf(d.file?.fileName);assert(i>=0,'Dependency diagnostic: '+d.file?.fileName+': '+ts.flattenDiagnosticMessageText(d.messageText,' '));groups[i].push(d.code)}const checker=p.getTypeChecker(),root=p.getSourceFile(mapping['@deepseek-ai/dsh-typert-protocol']);const surface=checker.getExportsOfModule(checker.getSymbolAtLocation(root)).map(s=>{const v=s.flags&ts.SymbolFlags.Alias?checker.getAliasedSymbol(s):s;return{name:s.name,type:!!(v.flags&ts.SymbolFlags.Type),value:!!(v.flags&ts.SymbolFlags.Value)}}).sort((a,b)=>a.name.localeCompare(b.name));return{groups,surface}}
 const original=check(originalMapping);assert.deepEqual(original.groups,cases.map(c=>c[2]),'exact original diagnostics');assert.deepEqual(check(candidateMapping),original,'complete native Protocol/Cordis/Brand SDK paired semantics');assert.equal(original.surface.filter(s=>s.value).length,13);assert.equal(original.surface.filter(s=>s.type).length,56);
 // Normalize only module layout and harmless formatting; preserve all declaration bodies, import owners, aliases, exports, private unique symbols and augmentation members.
 const logical=new Map(Object.entries(meta['module-files']).map(([name,file])=>[file.replace(/\.d\.mts$/,'.mjs'),name]));
 const moduleName=s=>s==='@deepseek-ai/cordis'?'cordis.index':s==='@deepseek-ai/dsh-brand'?'brand.index':s.startsWith('./')?(logical.get(s.slice(2))||'protocol.'+s.slice(2).replace(/\.ts$/,'').replaceAll('-','_')):s;
 function shape(n){if(ts.isParenthesizedTypeNode(n))return shape(n.type);if(ts.isIdentifier(n)||ts.isStringLiteral(n)||ts.isNumericLiteral(n))return{text:ts.isStringLiteral(n)&&(ts.isImportTypeNode(n.parent?.parent)||ts.isModuleDeclaration(n.parent))?moduleName(n.text):n.text};const children=[];ts.forEachChild(n,c=>{if(c.kind!==ts.SyntaxKind.DeclareKeyword&&!(c.kind===ts.SyntaxKind.ExportKeyword&&ts.isModuleBlock(n.parent)))children.push(shape(c))});return{kind:n.kind,children}}
 function normalized(file){const sf=ts.createSourceFile(file,readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),imports=[],exports=[],declarations=[];for(const n of sf.statements){if(ts.isImportDeclaration(n)){for(const e of n.importClause.namedBindings.elements)imports.push({module:moduleName(n.moduleSpecifier.text),type:!!(n.importClause.isTypeOnly||e.isTypeOnly),import:e.propertyName?.text||e.name.text,local:e.name.text});}else if(ts.isExportDeclaration(n)){if(!n.moduleSpecifier){assert.equal(n.exportClause.elements.length,0);continue}for(const e of n.exportClause.elements)exports.push({module:moduleName(n.moduleSpecifier.text),type:!!(n.isTypeOnly||e.isTypeOnly),import:e.propertyName?.text||e.name.text,export:e.name.text});}else declarations.push(shape(n))}return{imports:imports.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),exports:exports.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),declarations}}
 let count=0;for(const leaf of ['index','json-value','owned-value','remote-error','types']){const original=normalized(join(fixture,leaf+'.d.ts')),actual=normalized(join(candidate,meta['module-files']['protocol.'+leaf.replaceAll('-','_')]));assert.deepEqual(actual,original,'full original '+leaf+' structure and canonical owners');count+=original.declarations.length}assert.equal(count,86);
 console.log('Protocol SDK types: 16 positive/16 negative strict original-paired consumers, all 86 original declarations including Cordis augmentation, 13 values/56 public types, canonical full native Brand/Cordis owners; Node execution only.');
}finally{rmSync(dir,{recursive:true,force:true})}
