"Build the actual Kotoba dispatch policy with the pinned JVM-free compiler."
(import argparse pathlib os subprocess json hashlib tempfile)
(setv parser (argparse.ArgumentParser))
(.add-argument parser "--compiler-root" :required True)
(.add-argument parser "--output-dir" :required True)
(setv args (.parse-args parser) repo (get (getattr (.resolve (pathlib.Path __file__)) "parents") 1)
      bundle (.resolve (pathlib.Path args.compiler-root)) out (.resolve (pathlib.Path args.output-dir))
      source (/ repo "ports/policy.kotoba"))
(.mkdir out :parents True :exist-ok True)
(when (not (.exists (/ out "runtime"))) (.symlink-to (/ out "runtime") (/ bundle "amu/runtime") :target-is-directory True))
(setv classpath (.join os.pathsep (lfor p (json.loads (.read-text (/ bundle "classpath.json"))) (str (/ bundle p))))
      checks [])
(for [[entry argv] [["wasm_cli" ["compile" (str source) "--target" "wasm32-browser" "--output" (str (/ out "policy.wasm")) "--jvm-free"]]
                   ["test_cli" ["test" (str source) "--jvm-free" "--json" "--fuel" "10000"]]]]
  (setv r (subprocess.run (+ ["node" "--max-old-space-size=768" (str (/ bundle "engine/cli.js"))
                            "--classpath" classpath (str (/ bundle (+ "amu/src/kotoba/compiler/nbb/" entry ".cljk")))] argv)
            :cwd (str out) :text True :capture-output True :timeout 80))
  (.append checks {"entry" entry "exit" r.returncode "stdout" r.stdout "stderr" r.stderr})
  (when (!= r.returncode 0) (raise (RuntimeError (+ r.stdout r.stderr)))))
(setv manifest {"source-sha256" (.hexdigest (hashlib.sha256 (.read-bytes source)))
               "wasm" (str (/ out "policy.wasm"))
               "wasm-sha256" (.hexdigest (hashlib.sha256 (.read-bytes (/ out "policy.wasm"))))
               "checks" checks})
(.write-text (/ out "manifest.json") (json.dumps manifest :indent 2))
(print (str (/ out "manifest.json")))
