import assert from'node:assert/strict';import{readFileSync,writeFileSync,mkdtempSync,rmSync}from'node:fs';import{resolve,join,dirname}from'node:path';import{pathToFileURL,fileURLToPath}from'node:url';import{tmpdir}from'node:os';import{createHash}from'node:crypto';import{spawnSync}from'node:child_process';
const[manifest,compiler,typeRoots]=process.argv.slice(2),ts=(await import(pathToFileURL(resolve(compiler)))).default;assert.equal(ts.version,'6.0.3');const items=JSON.parse(readFileSync(manifest,'utf8')),fixture=fileURLToPath(new URL('../../../fixtures/mutable-declarations/',import.meta.url)),provenance=JSON.parse(readFileSync(join(fixture,'provenance.json'),'utf8')),original=readFileSync(resolve(fixture,'../schemastery-declarations/original-index.ts'),'utf8');assert.equal(createHash('sha256').update(original).digest('hex'),provenance.original_source_sha256);assert.equal(provenance.original_source_sha256,'a6647b515659cf439b701fa9f9574c9c310ce3872d26a13a81e9fa4d02ba10ad');for(const[f,h]of Object.entries(provenance.fixtures))assert.equal(createHash('sha256').update(readFileSync(join(fixture,f))).digest('hex'),h);
const dir=mkdtempSync(join(tmpdir(),'mithril-mutable-contract-'));try{
 for(const f of Object.keys(provenance.fixtures))writeFileSync(join(dir,f),readFileSync(join(fixture,f)));
 const opts={strict:true,skipLibCheck:false,target:ts.ScriptTarget.ES2024,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,declaration:true,outDir:join(dir,'oracle-output'),types:['node'],typeRoots:[resolve(typeRoots)]},oracle=ts.createProgram(Object.keys(provenance.fixtures).map(f=>join(dir,f)),opts);assert.deepEqual(ts.getPreEmitDiagnostics(oracle),[]);assert.equal(oracle.emit().emitSkipped,false);writeFileSync(join(dir,'oracle-output/package.json'),'{"type":"module"}');
 const positives=[['root numeric let','const n:number=api.count;'],['mutable aliases numeric','const n:number=api.alias;'],['bump return','const n:number=api.bump();'],['namespace mutable numeric','api.State.count=17;const n:number=api.State.count;'],['namespace refs set','api.State.refs={4:{value:1}};'],['namespace refs erase','api.State.refs=undefined;'],['namespace only-let write','api.OnlyMutable.slot=17;const n:number=api.OnlyMutable.slot;'],['namespace literal const read','const x:11=api.State.fixed;'],['global numeric query','const n:api.GlobalCounter=9;'],['global refs query','const n:api.GlobalRefs={7:{value:2}};'],['global refs undefined query','const n:api.GlobalRefs=undefined;'],['namespace value query','const n:api.StateRefs={9:{value:2}};'],['real global function result','const [n,r]=api.globalState({7:{value:1}});const x:number=n;const y:api.GlobalRefs=r;'],['undefined refs call','api.globalState(undefined);'],['query public let','const n:typeof api.count=17;'],['query alias let','const n:typeof api.alias=17;'],['inline let value query','const n:typeof import(ENTRY).count=17;']];
 const negatives=[['root wrong','const n:string=api.count;'],['alias wrong','const n:string=api.alias;'],['import namespace readonly','api.count=3;'],['namespace count wrong','api.State.count="x";'],['namespace refs wrong schema','api.State.refs={4:{value:"x"}};'],['namespace only-let wrong','api.OnlyMutable.slot="x";'],['namespace const readonly','api.State.fixed=11;'],['global counter wrong','const n:api.GlobalCounter="x";'],['global refs wrong helper','const n:api.GlobalRefs={7:{value:"x"}};'],['global missing params','api.globalState();'],['global wrong refs','api.globalState("x");'],['private namespace leak','api.globalThis.__schemastery_index__;'],['private local let leak','api.counter;'],['private type helper leak','type X=api.Schema;']];
 const extras=[['positive','forwarded mutable value','const n:number=api.forwarded;'],['positive','named mutable import query','const n:api.ImportedValue=1;'],['positive','namespace mutable import query','const n:api.NamespaceValue=1;'],['positive','inline mutable import query','const n:api.InlineValue=1;'],['negative','forwarded wrong','const n:string=api.forwarded;'],['negative','import value query wrong','const n:api.ImportedValue="x";']];
 const groups=[];for(const[index,item]of items.entries())for(const[category,name,body]of [...positives.map(([n,b])=>['positive',n,b]),...negatives.map(([n,b])=>['negative',n,b]),...(item.profile==='program'?extras:[])])for(const variant of ['original','candidate']){const entry=resolve(variant==='original'?join(dir,'oracle-output',item.profile==='program'?'index.js':item.profile==='function'?'function-a.js':'direct.js'):item.types.replace(/\.d\.mts$/,'.mjs')),file=join(dir,`consumer-${groups.length}.ts`);writeFileSync(file,'import * as api from '+JSON.stringify(entry)+';\n'+body.replaceAll('ENTRY',JSON.stringify(entry)));groups.push({index,category,name,variant,file})}
 const p=ts.createProgram(groups.map(g=>g.file),{...opts,noEmit:true}),ds=ts.getPreEmitDiagnostics(p),negative=new Set(groups.filter(g=>g.category==='negative').map(g=>g.file));assert.deepEqual(ds.filter(d=>!d.file||!negative.has(d.file.fileName)).map(d=>({file:d.file?.fileName,code:d.code,text:ts.flattenDiagnosticMessageText(d.messageText,' ')})),[]);
 for(const g of groups.filter(g=>g.category==='negative'&&g.variant==='original')){const c=groups.find(x=>x.index===g.index&&x.name===g.name&&x.variant==='candidate'),codes=x=>ds.filter(d=>d.file?.fileName===x.file).map(d=>d.code).sort((a,b)=>a-b);assert(codes(g).length,g.name);assert.deepEqual(codes(c),codes(g),g.name)}
 const checker=p.getTypeChecker(),surface=file=>checker.getExportsOfModule(checker.getSymbolAtLocation(p.getSourceFile(resolve(file)))).map(s=>{const x=s.flags&ts.SymbolFlags.Alias?checker.getAliasedSymbol(s):s;return{name:s.name,type:!!(x.flags&ts.SymbolFlags.Type),value:!!(x.flags&ts.SymbolFlags.Value)}}).sort((a,b)=>a.name.localeCompare(b.name));for(const item of items)assert.deepEqual(surface(item.types),surface(join(dir,'oracle-output',item.profile==='program'?'index.d.ts':item.profile==='function'?'function-a.d.ts':'direct.d.ts')));
 const parse=(s,n)=>ts.createSourceFile(n,s,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),globals=sf=>sf.statements.find(n=>ts.isModuleDeclaration(n)&&n.name.text==='globalThis'),fingerprint=n=>n.body.statements.filter(ts.isVariableStatement).flatMap(v=>v.declarationList.declarations.map(d=>({name:d.name.text,let:!!(v.declarationList.flags&ts.NodeFlags.Let),exported:!!v.modifiers?.some(m=>m.kind===ts.SyntaxKind.ExportKeyword),datatype:d.type.getText().replace(/[\s()]/g,'')})));
 const referenceGlobals=fingerprint(globals(parse(original,'original-index.ts')));assert.equal(referenceGlobals.length,2);assert(referenceGlobals.every(x=>x.let));
 for(const item of items){const entry=dirname(item.types),candidate=item.profile==='legacy'?item.types:join(entry,'module-0.d.mts');assert.deepEqual(fingerprint(globals(parse(readFileSync(candidate,'utf8'),candidate))),referenceGlobals);const sf=parse(readFileSync(candidate,'utf8'),candidate),counter=sf.statements.filter(ts.isVariableStatement).flatMap(v=>v.declarationList.declarations.map(d=>({name:d.name.text,let:!!(v.declarationList.flags&ts.NodeFlags.Let)}))).find(d=>d.name==='counter');assert.equal(counter.let,true)}
 const runner=fileURLToPath(new URL('./runtime-check.mjs',import.meta.url)),check=(entry,profile)=>{const r=spawnSync(process.execPath,[runner,entry,profile],{encoding:'utf8',timeout:60000});assert.equal(r.status,0,r.stdout+r.stderr);return JSON.parse(r.stdout)};for(const item of items){const ref=join(dir,'oracle-output',item.profile==='program'?'index.js':item.profile==='function'?'function-a.js':'direct.js');assert.deepEqual(check(item.runtime,item.profile),check(ref,item.profile))}
 console.log(`Mutable declaration oracle:${groups.length/2} paired strict logical groups across${items.length} CLI declaration artifacts;two hashed original globalThis let declarations under explicit Schema helper;fresh-process paired runtime surfaces/live root aliases/namespace mutations/global state and readonly module namespace;${items.length} paired runtime scenarios,not full Schemastery or global augmentation.`);
}finally{rmSync(dir,{recursive:true,force:true})}
