import assert from 'node:assert/strict';import{readFileSync,mkdtempSync,rmSync,realpathSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{pathToFileURL}from'node:url';import{runInNewContext}from'node:vm';import{toolchain,originalRuntime}from'./support.mjs';
const[compiler,sdk]=process.argv.slice(2),ts=await toolchain(resolve(compiler)),candidate=resolve(sdk),meta=JSON.parse(readFileSync(candidate+'.log','utf8')),dir=realpathSync(mkdtempSync(join(tmpdir(),'attachment-runtime-')));try{originalRuntime(join(dir,'original'),ts);const original=await import(pathToFileURL(join(dir,'original/index.mjs'))),actual=await import(pathToFileURL(join(candidate,'index.mjs'))),oc=await import(pathToFileURL(join(dir,'original/node_modules/@deepseek-ai/cordis/index.mjs'))),ac=await import(pathToFileURL(join(candidate,meta['module-files'].cordis)));assert.deepEqual(Object.keys(actual).sort(),Object.keys(original).sort());assert.equal(Object.keys(actual).length,11);assert.equal(actual.default,actual.AttachmentStore);assert.equal(original.default,original.AttachmentStore);
 const shape=o=>Reflect.ownKeys(o).map(key=>{const d=Object.getOwnPropertyDescriptor(o,key);return{key:typeof key==='symbol'?String(key):key,enumerable:d.enumerable,configurable:d.configurable,writable:d.writable,value:typeof d.value==='function'?{name:d.value.name,length:d.value.length}:typeof d.value,get:d.get&&{name:d.get.name,length:d.get.length},set:d.set&&{name:d.set.name,length:d.set.length}}});for(const name of Object.keys(original)){assert.deepEqual(shape(actual[name]),shape(original[name]));if(original[name].prototype)assert.deepEqual(shape(actual[name].prototype),shape(original[name].prototype));}
 async function groups(api,cordis){const results=[];for(const name of ['AttachmentId','ImageVariantId'])for(const value of [undefined,null,false,true,'','id',0,-0,NaN,Infinity,1n,Symbol.for('id'),{},[],new String('x')]){assert.ok(Object.is(api[name](value),value));results.push(name+':identity')}
 for(const w of [1,2,17,320,4096,8000])for(const h of [1,4,33,240,2160,9000])for(const cap of [1,5,640000]){const result=api.requestImageDimensions(w,h,cap);results.push(result)}for(const[w,h]of [[1,9000],[8000,40],[1080,2400],[320,240]])for(const edge of [1,320,1862,4096])results.push(api.longEdgeDimensions(w,h,edge));
 for(const code of ['INVALID_IMAGE','INVALID_IMAGE_BASE64','INVALID_FILE_BASE64','TOO_MANY_IMAGES','IMAGES_TOO_LARGE','UNSUPPORTED_IMAGE_TYPE','IMAGE_TYPE_MISMATCH','IMAGE_TOO_LARGE','IMAGE_TOO_MANY_PIXELS','IMAGE_DIMENSION_TOO_LARGE','INVALID_ATTACHMENT_REF','ATTACHMENT_CORRUPT','ATTACHMENT_WRITE_FAILED','ATTACHMENT_NOT_FOUND','ATTACHMENT_READ_FAILED','ATTACHMENT_PROJECTION_UNSUPPORTED','ATTACHMENT_FILES_UNSUPPORTED','OTHER']){const e=new api.AttachmentError('message',code,{cause:'cause'});assert.ok(e instanceof Error);assert.equal(e.cause,'cause');results.push([e.name,e.message,e.code,e.cause,api.isAttachmentError(e),api.isImageAdmissionError(e),shape(e)]);const foreign=Object.assign(new Error('foreign'),{code});results.push([api.isAttachmentError(foreign),api.isImageAdmissionError(foreign)]);}
 for(const value of [null,undefined,{}, {code:'INVALID_IMAGE'},Object.create({code:'INVALID_IMAGE'}),runInNewContext('Object.assign(new Error("remote"),{code:"INVALID_IMAGE"})')])results.push([api.isAttachmentError(value),api.isImageAdmissionError(value)]);
 const ctx=new cordis.Context();class Store extends api.AttachmentStore{imageLimits={maxImageBytes:4,maxImagesPerMessage:2,maxMessageImageBytes:5,maxImagePixels:4,maxImageDimension:2000,mediaTypes:['image/png']};validateImage(){return Promise.resolve()}saveImage(){throw new Error('not used')}readImage(){throw new Error('not used')}}const store=new Store(ctx);assert.ok(store instanceof cordis.Service);results.push([ctx.attachments!==store,ctx.attachments instanceof Store,ctx.attachments instanceof cordis.Service]);assert.equal(store.imageHostPath({}),undefined);assert.equal(store.fileHostPath({}),undefined);results.push('canonical Service and Context');let calls=0;store.saveFile=async input=>{calls++;assert(input.data instanceof Uint8Array);return{attachmentId:api.AttachmentId('id'),bytes:input.data.length,data:[...input.data],hasName:Object.hasOwn(input,'name')}};
 for(const data of ['','AAAA','AQID','AA==','AAA=','AAA','AA','!!!!','AA==\n']){try{results.push(await api.admitEncodedFile(store,{data}))}catch(e){results.push([e.name,e.message,e.code])}}results.push(calls);const reason=new Error('cancelled'),signal=AbortSignal.abort(reason);assert.throws(()=>store.readImageRequest({}, {width:1,height:1,maxBytes:1},signal),e=>e===reason);await ctx.fiber.dispose();return results;}
 const expected=await groups(original,oc),candidateGroups=await groups(actual,ac);assert.deepEqual(candidateGroups,expected);assert.equal(candidateGroups.length,208);console.log('Attachment runtime: '+candidateGroups.length+' full-source original-paired groups, exact class/function descriptors and default identity, canonical native Cordis, structural errors/cross-realm policy, real node:buffer byte admission and projection geometry; Node execution only.');
}finally{rmSync(dir,{recursive:true,force:true})}
